In [ ]:
                         # Module 1

In [2]:
#Import the required libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [21]:
#Load purchase_orders.csv into a DataFrame named purchase_orders.
df=pd.read_csv(r"C:\Users\yadav\Documents\archive (3)\purchase_orders.csv")
#Display the first 5 rows.
df.head()
#Display the last 5 rows.
df.tail()
#Display the number of rows and columns.
df.shape
#Display all column names.
df.columns
#Show the data types of each column.
df.dtypes
#Display summary information .
df.info()
#Display descriptive statistics
df.describe()
#Count missing values in each column.
df.isnull().sum()
#Count the total number of missing values in the dataset.
df.isnull().sum().sum()
#Count duplicate rows.
df.duplicated().sum()
#Display all duplicate rows (
df[df.duplicated()]
#Display only these columns :po_id supplier_id ordered_qty
df[["po_id","supplier_id","ordered_qty"]]
#Display all purchase orders where: ordered_qty > 100
df[df["ordered_qty"]>100]
#Display all purchase orders where: site_id == 'DEN'
df[df["site_id"]=='DEN']
#Display all purchase orders where: ordered_qty > 100 AND site_id == 'DEN'
df[(df["ordered_qty"]>100) & (df["site_id"]=='DEN')]
#Display only the following columns for the filtered result : po_id supplier_id ordered_qty
Filtered_df=df[(df["ordered_qty"]>100) & (df["site_id"]=='DEN')]
Filtered_df[["po_id","supplier_id","ordered_qty"]]

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29666 entries, 0 to 29665
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   po_id          29666 non-null  object
 1   supplier_id    29666 non-null  object
 2   site_id        29666 non-null  object
 3   part_id        29666 non-null  object
 4   order_date     29666 non-null  object
 5   promised_date  29666 non-null  object
 6   receipt_date   29666 non-null  object
 7   ordered_qty    29666 non-null  int64
 8   received_qty   29666 non-null  int64
dtypes: int64(2), object(7)
memory usage: 2.0+ MB

Empty DataFrame
Columns: [po_id, supplier_id, ordered_qty]
Index: []

In [31]:
#Show the top 10 purchase orders with the highest ordered_qty.
df=df.sort_values("ordered_qty")
df.tail(10)
df.nlargest(10,"ordered_qty")
#Show the top 10 purchase orders with the lowest ordered_qty.
df=df.sort_values("ordered_qty")
df.head(10)
df.nsmallest(10,"ordered_qty")
#Find the average ordered quantity.
df["ordered_qty"].mean()
#Find the maximum ordered quantity.
df["ordered_qty"].max()
#Find the minimum ordered quantity.
df["ordered_qty"].min()

1

In [15]:
#Create a supplier summary report Total Purchase Orders Total Ordered Quantity Total Receive Quantity Average Ordered Quantity Average Received Quantity Maximum Ordered Quantity Minimum Ordered Quantity
df=pd.read_csv(r"C:\Users\yadav\Documents\archive (3)\purchase_orders.csv")
df.columns
df.groupby("supplier_id").agg(Total_PO=("po_id","count"),Total_Ordered=("ordered_qty","sum"),
                              Total_Received=("received_qty","sum"),
                              Avg_Ordered=("ordered_qty","mean"),
                              Max_Ordered=("ordered_qty","max"),
                              Min_Ordered=("ordered_qty","min"),
                              Avg_Received=("received_qty","mean")
).sort_values("Total_Ordered",ascending=False)

,Total_PO,Total_Ordered,Total_Received,Avg_Ordered,Max_Ordered,Min_Ordered,Avg_Received
supplier_id,,,,,,,
SUP027,1311,23791,22955,18.147216,160,1,17.509535
SUP017,1306,21270,20763,16.286371,123,1,15.898162
SUP038,967,18714,18054,19.352637,201,1,18.670114
SUP040,1215,16905,16303,13.913580,97,1,13.418107
SUP006,1096,16781,16159,15.311131,139,1,14.743613
SUP030,1171,16462,16156,14.058070,95,1,13.796755
SUP024,821,16150,15587,19.671133,128,2,18.985384
SUP002,763,15601,15100,20.446920,138,1,19.790301
SUP036,840,15202,14834,18.097619,92,1,17.659524
SUP012,1163,14886,14705,12.799656,104,1,12.644024
SUP013,1156,14293,13772,12.364187,66,1,11.913495
SUP028,793,13934,13636,17.571248,224,1,17.195460
SUP014,843,13834,13365,16.410439,156,1,15.854093
SUP010,930,13221,12946,14.216129,101,1,13.920430
SUP009,649,11741,11357,18.090909,173,2,17.499230
SUP037,842,10929,10649,12.979810,91,1,12.647268
SUP035,699,10611,10405,15.180258,110,1,14.885551
SUP026,680,10582,10232,15.561765,105,1,15.047059
SUP007,831,10503,10315,12.638989,88,1,12.412756
SUP022,730,10481,10235,14.357534,119,1,14.020548
SUP008,587,9797,9554,16.689949,111,1,16.275980
SUP003,633,9558,9261,15.099526,106,1,14.630332
SUP021,523,9353,8919,17.883365,263,1,17.053537
SUP029,684,8889,8741,12.995614,86,1,12.779240
SUP031,803,8848,8687,11.018680,79,1,10.818182
SUP018,607,8804,8511,14.504119,115,1,14.021417
SUP004,662,8703,8556,13.146526,91,1,12.924471
SUP011,565,8563,8386,15.155752,80,1,14.842478
SUP033,631,8272,7810,13.109350,126,1,12.377179
SUP001,659,7839,7650,11.895296,156,1,11.608498
SUP019,691,7604,7450,11.004342,73,1,10.781476
SUP025,543,7031,6745,12.948435,97,1,12.421731
SUP034,578,6349,6218,10.984429,89,1,10.757785
SUP020,433,5495,5414,12.690531,58,2,12.503464
SUP016,385,5420,5226,14.077922,99,1,13.574026
SUP032,441,5007,4944,11.353741,131,1,11.210884
SUP005,436,4791,4556,10.988532,102,1,10.449541
SUP015,413,3536,3430,8.561743,54,1,8.305085
SUP023,280,2607,2510,9.310714,51,1,8.964286
SUP039,306,2342,2241,7.653595,42,1,7.323529

In [28]:
#Calculate: Total Purchase Orders Total Ordered Quantity Total Received Quantity Average Ordered Quantity Average Received Quantity
import pandas as pd

df = pd.read_csv(r"C:\Users\yadav\Documents\archive (3)\purchase_orders.csv")

summary = df.groupby(["supplier_id", "site_id"]).agg(
    Total_PO=("po_id", "count"),
    Total_Ordered=("ordered_qty", "sum"),
    Total_Received=("received_qty", "sum"),
    Avg_Ordered=("ordered_qty", "mean"),
    Max_Ordered=("ordered_qty", "max"),
    Min_Ordered=("ordered_qty", "min"),
    Avg_Received=("received_qty", "mean")
).sort_values("Total_Ordered", ascending=False)

print(summary)

                     Total_PO  Total_Ordered  Total_Received  Avg_Ordered  \
supplier_id site_id
SUP027      SITE06        316           7873            7589    24.914557
SUP038      SITE04        205           6596            6333    32.175610
SUP027      SITE04        283           6489            6262    22.929329
SUP017      SITE06        295           6479            6313    21.962712
SUP030      SITE04        275           5604            5505    20.378182
...                       ...            ...             ...          ...
SUP016      SITE01         41            218             215     5.317073
SUP015      SITE02         47            207             197     4.404255
SUP023      SITE02         34            187             180     5.500000
            SITE05         34            184             177     5.411765
            SITE01         31            145             137     4.677419

                     Max_Ordered  Min_Ordered  Avg_Received
supplier_id site_id
SUP027      SITE06           126            1     24.015823
SUP038      SITE04           168            2     30.892683
SUP027      SITE04           160            1     22.127208
SUP017      SITE06            98            2     21.400000
SUP030      SITE04            95            1     20.018182
...                          ...          ...           ...
SUP016      SITE01            22            1      5.243902
SUP015      SITE02            22            1      4.191489
SUP023      SITE02            18            1      5.294118
            SITE05            14            1      5.205882
            SITE01            11            2      4.419355

[240 rows x 7 columns]

In [9]:
#Create a new column called Order_Status based on the following rules:
#If received_qty == ordered_qty → "Complete"
#If received_qty == 0 → "Not Received"
#Otherwise → "Partial"
import numpy as np 
import pandas as pd 
df = pd.read_csv(r"C:\Users\yadav\Documents\archive (3)\purchase_orders.csv")
df["order_status"]=np.where(df["received_qty"]==df["ordered_qty"],"complete",
                   np.where(df["received_qty"]==0,"not received","partial"))
print(df[["po_id","ordered_qty","received_qty","order_status"]].head(10))
df.groupby(["supplier_id","order_status"]).agg(Total_PO=("po_id", "count"),
    Total_Ordered=("ordered_qty", "sum"),
    Total_Received=("received_qty", "sum")).sort_values("Total_Ordered", ascending=False)

      po_id  ordered_qty  received_qty order_status
0  PO000001           16            16     complete
1  PO000002            5             5     complete
2  PO000003            5             5     complete
3  PO000004            3             3     complete
4  PO000005            5             5     complete
5  PO000006            5             5     complete
6  PO000007            4             4     complete
7  PO000008           13            13     complete
8  PO000009            4             4     complete
9  PO000010            8             8     complete

                          Total_PO  Total_Ordered  Total_Received
supplier_id order_status
SUP027      complete          1120          20038           20038
SUP017      complete          1183          19027           19027
SUP038      complete           826          15947           15947
SUP030      complete          1074          15035           15035
SUP040      complete          1026          14366           14366
...                            ...            ...             ...
SUP015      partial             49            471             365
SUP039      partial             45            449             348
SUP023      partial             37            370             273
SUP020      partial             29            358             277
SUP032      partial             23            259             196

[80 rows x 3 columns]

In [18]:
import numpy as np
import pandas as pd 
purchase_df=pd.read_csv(r"C:\Users\yadav\Documents\archive (3)\purchase_orders.csv")
master_df=pd.read_csv(r"C:\Users\yadav\Documents\archive (3)\parts_master.csv")
merge_df=pd.merge(purchase_df,master_df,on="part_id",how='inner')
print(merge_df[["po_id","supplier_id","part_id","ordered_qty","criticality_class","unit_cost","is_repairable"]])

          po_id supplier_id part_id  ordered_qty criticality_class  unit_cost  \
0      PO000001      SUP004  P00001           16                 B    2323.45
1      PO000002      SUP004  P00001            5                 B    2323.45
2      PO000003      SUP004  P00001            5                 B    2323.45
3      PO000004      SUP004  P00001            3                 B    2323.45
4      PO000005      SUP004  P00001            5                 B    2323.45
...         ...         ...     ...          ...               ...        ...
29661  PO029662      SUP035  P00300           33                 B    3351.06
29662  PO029663      SUP035  P00300            9                 B    3351.06
29663  PO029664      SUP035  P00300            9                 B    3351.06
29664  PO029665      SUP035  P00300           35                 B    3351.06
29665  PO029666      SUP035  P00300           18                 B    3351.06

      is_repairable
0                No
1                No
2                No
3                No
4                No
...             ...
29661            No
29662            No
29663            No
29664            No
29665            No

[29666 rows x 7 columns]

In [ ]:
                                      # Module 2

In [1]:
import numpy as np
import pandas as pd
#Data Cleaning & Data Transformation

df=pd.read_csv(r"C:\Users\yadav\Documents\archive (3)\purchase_orders.csv")
df.isnull().sum()
df.isnull().sum().sum()
df[df.isnull().any(axis=1)]
df.isnull().sum()/len(df)*100.0

#Handling Missing Values

df["receipt_date"].isnull().sum()
df["receipt_date"]=df["receipt_date"].fillna('pending')
df["receipt_date"].isnull().sum()
print(df[["po_id","receipt_date"]].head(15))

#Dropping Missing Values
df=pd.read_csv(r"C:\Users\yadav\Documents\archive (3)\purchase_orders.csv")
df.shape
df = df.dropna(subset=["receipt_date"])
df.shape
df["receipt_date"].isnull().sum()

       po_id receipt_date
0   PO000001   2022-05-29
1   PO000002   2022-08-02
2   PO000003   2022-11-16
3   PO000004   2023-03-09
4   PO000005   2023-04-29
5   PO000006   2023-12-17
6   PO000007   2024-01-01
7   PO000008   2024-05-30
8   PO000009   2024-06-21
9   PO000010   2024-08-21
10  PO000011   2024-10-06
11  PO000012   2022-05-10
12  PO000013   2022-06-11
13  PO000014   2022-07-20
14  PO000015   2022-09-06

np.int64(0)

In [17]:
#Removing Duplicate Records
import numpy as np
import pandas as pd
df=pd.read_csv(r"C:\Users\yadav\Documents\archive (3)\purchase_orders.csv")
df.shape
df.duplicated().sum()
df[df.duplicated()]
df=df.drop_duplicates()
df.shape
#Date Handling & Date Arithmetic
df["order_date"]=pd.to_datetime(df["order_date"])
df["promised_date"]=pd.to_datetime(df["promised_date"])
df["receipt_date"]=pd.to_datetime(df["receipt_date"])
df["Delivery_Days"] = df["receipt_date"] - df["order_date"]
df["Delay_Days"] = (df["receipt_date"] - df["promised_date"]).dt.days
print(df[["po_id","supplier_id","order_date","promised_date","receipt_date","Delivery_Days","Delay_Days"]])

#Apply Function
def classify_orders(ordered_qty):
    if ordered_qty < 100:
        return "small"
    elif 100 <= ordered_qty <300:
        return "medium"
    else :
        return "large"

df["order_size"]=df["ordered_qty"].apply(classify_orders)
print(df[["po_id","ordered_qty","order_size"]])

          po_id supplier_id order_date promised_date receipt_date  \
0      PO000001      SUP004 2022-05-02    2022-05-28   2022-05-29
1      PO000002      SUP004 2022-07-04    2022-07-31   2022-08-02
2      PO000003      SUP004 2022-10-17    2022-11-12   2022-11-16
3      PO000004      SUP004 2023-02-06    2023-03-07   2023-03-09
4      PO000005      SUP004 2023-04-03    2023-04-28   2023-04-29
...         ...         ...        ...           ...          ...
29661  PO029662      SUP035 2024-08-12    2024-09-13   2024-09-13
29662  PO029663      SUP035 2024-08-19    2024-09-20   2024-09-19
29663  PO029664      SUP035 2024-09-30    2024-10-31   2024-10-28
29664  PO029665      SUP035 2024-11-25    2025-01-01   2024-12-29
29665  PO029666      SUP035 2024-12-02    2024-12-28   2024-12-25

      Delivery_Days  Delay_Days
0           27 days           1
1           29 days           2
2           30 days           4
3           31 days           2
4           26 days           1
...             ...         ...
29661       32 days           0
29662       31 days          -1
29663       28 days          -3
29664       34 days          -3
29665       23 days          -3

[29666 rows x 7 columns]
          po_id  ordered_qty order_size
0      PO000001           16      small
1      PO000002            5      small
2      PO000003            5      small
3      PO000004            3      small
4      PO000005            5      small
...         ...          ...        ...
29661  PO029662           33      small
29662  PO029663            9      small
29663  PO029664            9      small
29664  PO029665           35      small
29665  PO029666           18      small

[29666 rows x 3 columns]